stages:
  - build
  - test
build:
  stage: build
  script:
    - cd group-01
    - ./gradlew assemble
test:
  stage: test
  script:
    - cd group-01
    - ./gradlew test
  dependencies:
    - build

