stages:
  - build
  - test
  - sonarqube
build:
  stage: build
  script:
    - ./gradlew assemble
test:
  stage: test
  script:
    - ./gradlew test
  dependencies:
    - build
sonarqube:
  stage: sonarqube
  script:
    - cd group-01
    - ./gradlew sonarqube
  dependencies:
    - test

